feat(add_facility ): facility drafts
energywebfoundation/zero pull request #56
Opened 2021-09-22 10:14 UTC by arkadiusz-s

* Image List
* Facility form draft save
* Facility form draft update

2021-09-22 10:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/energywebfoundation/zero?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/energywebfoundation/zero?pullRequest=56) before we can accept your contribution.<br/><hr/>**Arkadiusz Szaleniec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/energywebfoundation/zero?pullRequest=56) it.</sub>

2021-09-22 12:40 UTC, alexworker23 requested changes

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/components/seller-add-facilities-basic-information-form/seller-add-facilities-basic-information-form.tsx
>  const StyledSellerAddFacilitiesBasicInformationForm = styled.div``;
Why do we need styled div with empty styling ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/components/seller-add-facilities-images-form/seller-add-facilities-images-form.tsx
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
Why do you add this rule disabling ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/components/seller-add-facilities-images-form/seller-add-facilities-images-form.tsx
>  /* eslint-disable-next-line */
Why have this rule disabling ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/pages/seller-add-facilities-basic-information-page/seller-add-facilities-basic-information-page.tsx
>    submitHandler,
What is the point of this wrapper component ? Since you are only wrapping `SellerAddFacilitiesBasicInformationForm` in a non-styled div

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/pages/seller-add-facilities-page/seller-add-facilities-page.tsx
>  export interface SellerAddFacilitiesPagePropsEnum {}
What is the point of storing this interface ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/pages/seller-add-facilities-page/seller-add-facilities-page.tsx
>                      console.log(values);
- why async if you are not awaiting anything? 
- console.log rm
Same goes to several forms below in this file ⬇️

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/pages/seller-add-facilities-page/seller-add-facilitites.effects.ts
> +  console.log(showDraftSavedMsg);
console.log rm

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/pages/seller-add-facilities-page/seller-add-facilitites.effects.ts
> +        data: facilityDraft as any,
Why as `any`?

2021-09-22 12:40 UTC, alexworker23 commented on libs/seller/src/pages/seller-add-facilities-page/seller-add-facilitites.effects.ts
> +          const { id } = res as { id: number };
Why do you have to add types here? It should be automatically supplied on auto-gen

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/disabled-overlay/disabled-overlay.tsx
> +    <StyledDisabledOverlay>
Why do you have to store not used components ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/file-info/file-info.tsx
>  const StyledFileInfo = styled(Box)``;
What is the point of creating this component with empty styling?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/file-info/file-info.tsx
> +  console.log(id);
Console.log rm

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/generic-form-step-list/generic-form-multi-step.tsx
> +            return null;
What is the reason  for having this, since it return only `null` and does not modify anything?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/green-label-list-item/green-label-list-item.tsx
> +    greenLabelType: GreenLabelTypeEnum,
Why not specify this in empty GreenLabelListItemProps interface above ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/green-label-list-item/green-label-list-item.tsx
> +          submitHandler={async (values, resetForm) => {}}
Why this submitHandler is missing?

reply: cause this is actually locked form.

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/image-item/image-item.tsx
> +        bgcolor={lightPlaceholder ? '#F6EFFF' : 'primary'}
Why don't you have this color specified in theme ? I guess you are using this a lot

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/components/image-list/image-list.tsx
> +          <ImageItem src={'xx'} showLightPlaceholder />
Why do we have is as a dummy component? What is missing for it to be implemented ?

reply: I actually forgot to remove this dummy src. Fixed

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/facility-document-list-container/facility-document-list-container.tsx
> +  const [list, setList] = useState<FacilityDocumentDto[]>(data);
Are you sure that this data will be received as initial state? 
If this is received asynchronously there is a high chance of it being undefined, unless you are blocking the render until the data fetch is ended.

reply: Yes i am sure. initial data is just an empty array.

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/facility-document-list-container/facility-document-list-container.tsx
> +      handleFileListChanged={noop}
Why not implemented?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/file-list-container/file-list-container.effects.ts
> +    handleDeleteRequest: (filename: string) => {},
What is the reason for not implementing this part?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/generic-form-container/generic-form-container.effects.tsx
>    // eslint-disable-next-line @typescript-eslint/ban-types
Why add this eslint disable?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/image-list-container/image-list-container.tsx
> +    .map((el) => (el as any)?.url);
Why as `any`?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/image-upload-container/image-upload-container.effects.ts
> +      console.log(acceptedFiles, fileRejections, event);
console.log rm

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/image-upload-container/image-upload-container.effects.ts
> +  console.log({ isLoading });
console.log rm

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/image-upload-container/image-upload-container.tsx
> +              A JPG or PNG image must not be more than 4,000 pixels wide high,
Why not localized?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/containers/processing-container/processing-container.tsx
> +        <CircularProgress sx={{ opacity: 1 }} color={'primary'} />
Is CircularProgress having default opacity of lower than 1 ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/core/src/lib/pages/facility-draft-list-page/facility-draft-list-page.tsx
> +  return <StyledFacilityDraftListPage></StyledFacilityDraftListPage>;
Why store empty pages ?

2021-09-22 12:40 UTC, alexworker23 commented on libs/ui/zero-api/src/response-type.ts
> +      console.log(res);
console.log rm

2021-09-23 12:53 UTC, arkadiusz-s commented on libs/ui/core/src/lib/pages/facility-draft-list-page/facility-draft-list-page.tsx
> +  return <StyledFacilityDraftListPage></StyledFacilityDraftListPage>;
added partial implementation.

2021-09-23 13:02 UTC, arkadiusz-s commented on libs/seller/src/pages/seller-add-facilities-page/seller-add-facilitites.effects.ts
> +          const { id } = res as { id: number };
Yes, but i get unknown

2021-09-23 13:04 UTC, arkadiusz-s commented on libs/ui/core/src/lib/components/image-item/image-item.tsx
> +        bgcolor={lightPlaceholder ? '#F6EFFF' : 'primary'}
This is good point to fix though, will create chore for this.

2021-09-23 13:04 UTC, arkadiusz-s commented on libs/ui/core/src/lib/containers/facility-document-list-container/facility-document-list-container.tsx
> +      handleFileListChanged={noop}
its not needed in this context.

2021-09-23 13:05 UTC, arkadiusz-s commented on libs/ui/core/src/lib/containers/file-list-container/file-list-container.effects.ts
> +    handleDeleteRequest: (filename: string) => {},
waiting for the design.

2021-09-23 13:05 UTC, arkadiusz-s commented on libs/ui/core/src/lib/containers/generic-form-container/generic-form-container.effects.tsx
>    // eslint-disable-next-line @typescript-eslint/ban-types
it doesnt accept object otherwise.

2021-09-23 14:24 UTC, alexworker23 commented on libs/seller/src/pages/seller-add-facilities-page/seller-add-facilitites.effects.ts
> +          const { id } = res as { id: number };
Should not be the case, if on the backend types are correct

2021-09-23 14:27 UTC, alexworker23 approved these changes

2021-09-23 14:56 UTC, merged